version: '3.8'
services:
    nginx-fc:
        image: nginx
        volumes:
            - ./web-server/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        depends_on: 
            - server
        links:
            - server
    server:
        build:
            context: .
        env_file: ./.env
        command: npm start
        volumes: 
            - .:/app/
            - /app/node_modules
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        depends_on: 
            mysqldb:
                condition: service_healthy
        environment: 
            MYSQL_HOST: mysqldb
    mysqldb:
        image: mysql
        env_file: ./.env
        environment: 
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
        ports:
            - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
        volumes:
            - ./database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          timeout: 20s
          retries: 10

volumes:
    mysql:
    mysql_config: